spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://10.18.32.90:3306/copy_test?characterEncoding=utf-8
    username: test
    password: test
    slave1:
      jdbc-url: jdbc:mysql://10.18.32.90:3307/copy_test?characterEncoding=utf-8
      username: test
      password: test
    slave2:
      jdbc-url: jdbc:mysql://10.18.32.90:3308/copy_test?characterEncoding=utf-8
      username: test
      password: test